dataset_dir: 
# optimization
warmup_step: 10
max_grad_norm: 10.0

rand_bg: False

# add configuration for force
center_point: [0.076272, 0.848310, 0.074134] # top of the flower
force_dir: [1.0, 0.0, 0.0]
force_mag: 0.1
force_duration: 4.3e-5
force_radius: 0.1
