dataset_dir: 
# optimization
warmup_step: 10
max_grad_norm: 10.0

rand_bg: False

velo_dir: [
  "../../data/physics_dreamer/alocasia_nerfstudio/mul_videos/velopretrain_models/frame_00037_mb-8_fps-30_8",
  # "/data/ruihan/projects/PhysDreamer/data/physics_dreamer/alocasia",
]

# add configuration for force
center_point: [0.076272, 0.848310, 0.074134]
force_dir: [1.0, 0.0, 0.0]
force_mag: 5e-6
force_duration: 0.75
force_radius: 0.1
